### ISSUE TITLE
Different modes

### ISSUE THREAD

**Issue by tinuva** [drkno/cloudmount#3]
Is "rclone" the only mode that currently works with cloudmount?

What value is needed to use plexdrive if it is supported?

Thank you in advance.

**Comment by drkno** [comment]
Any value for "mode" other than "rclone" [will use plexdrive](https://github.com/drkno/cloudmount/blob/14b69a44bc6fa440be526f9c87baa32afb7e8917/src/fs/usr/bin/mount.script#L83).

Note that I don't use it in that way anymore so I have no idea if it still works. rclone seems to get significantly higher throughput for me with its vfs cache options.

**Comment by tinuva** [comment]
Ah right. I tried that and somewhere something on the mounts fail. I have gone back to rclone mode and will see how it works out.

Thank you. Can close this issue then.
